kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv-postgres"  # change path to a folder on your computer (or VirtualBox VM)
