apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres
