apiVersion: v1
kind: LimitRange
metadata:
  name: lr-multi
spec:
  limits:
  - type: Container
    default:
      cpu: 1
    defaultRequest:
      cpu: 500m
  - type: Pod
    max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 500Mi
      cpu: 100m
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 10Gi

