kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: mongo-ops-db-00
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: nfsmongo
    hostPath:
      path: "/data/pv-mongodb-0"
    # nfs:
    #   server: server
    #   path: "/var/lib/docker/nfsexport/mongo-ops-db-01"
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: mongo-ops-db-01
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: nfsmongo
    hostPath:
      path: "/data/pv-mongodb-1"
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: mongo-ops-db-02
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: nfsmongo
    hostPath:
      path: "/data/pv-mongodb-2"
