apiVersion: v1
kind: Secret
metadata:
  name: my-image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJwaXBwbyIsInBhc3N3b3JkIjoicGFzc3dvcmQiLCJlbWFpbCI6ImVtYWlsQGRvbWFpbi5jb20iLCJhdXRoIjoiY0dsd2NHODZjR0Z6YzNkdmNtUT0ifX19
