apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poddoz-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poddoz
  template:
    metadata:
      labels:
        app: poddoz
    spec:
      containers:
      - name: poddoz-secret
        image: nicobenaz/k8s-demo/poddoz:3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: tls-certs
          mountPath: "/tls"
          readOnly: true
      imagePullSecrets:
      - name:  my-image-pull-secret
      volumes:
        - name: tls-certs
          secret:
            secretName: my-secret
